### ISSUE TITLE
Initiatives List 

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-initiatives#1]
AS a user
TO view the initiatives
NEED TO have a page on the site where all active initiatives are displayed

**Comment by jsperezg** [comment]
Tests needed.

**Comment by arnaumonty** [comment]
The label in each  closed initiative for should show the label: 
- accepted (the initiative has got enough signatures)
- expired (the initiative hasn't got enough signatures)

We do not show any label for each opened initiative.

**Comment by jsperezg** [comment]
This is already fixed but not deployed yet in staging repository.
