### ISSUE TITLE
Detail initiative - Comments

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-initiatives#10]
AS a user
IN ORDER TO view the comments that have been made in an initiative
NEED the initiative detail page and the registered users comments will be displayed. Users will be able to comment the initiative as well.
CRITERIA OF ACCEPTANCE
- View and comment on an initiative
- It will be implemented using the already existing module 'decidim-comments'

**Comment by jsperezg** [comment]
Done using the already existing component in Decidim framework.

**Comment by jsperezg** [comment]
Needs validation

**Comment by arnaumonty** [comment]
Add Up and Down votes in comments and +, - or neutral comments.

**Comment by jsperezg** [comment]
@arnaumonty The features that you mention in your last comment have been enabled in the last version.
