### ISSUE TITLE
Random failures  during test executions

### ISSUE THREAD

**Issue by jsperezg** [decidim/decidim-initiatives#109]
# This is a Bug Report 

Specs for this project fail randomly, even if tests are repeated using the same seed. See attached images bellow:

#### :clipboard: Additional Data

* ***Screenshot***:
![seleccion_014](https://user-images.githubusercontent.com/1701962/35912645-715cbdc2-0bfd-11e8-86ef-985ea12ef970.png)

![seleccion_015](https://user-images.githubusercontent.com/1701962/35912650-76191f2c-0bfd-11e8-9864-b9e288ac15ac.png)

**Comment by jsperezg** [comment]
@josepjaume @deivid-rodriguez any clue of what might be  happening? Have you ever  seen something similar?

**Comment by josepjaume** [comment]
No! Actually, the tests of `decidim` are currently pretty robust - there's a single flaky test we're trying to solve. It must have to do with some subtlety of the tests of that project. Did my research but couldn't figure it out. I'll give it another try!
