### ISSUE TITLE
Detail initiative - Organizations supporting

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-initiatives#11]
AS a user
IN ORDER To see the list of organizations that support an initiative
I NEED the initiative detail page shows the organizations that support the initiative
CRITERIA OF ACCEPTANCE
- Be able to visualize the organizations that support an initiative including his logo

**Comment by jsperezg** [comment]
Almost finished. The UI needs some revission and tests whould be written as well.

**Comment by jsperezg** [comment]
Needs validation
