### ISSUE TITLE
Detail Initiative - Promoter Committee

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-initiatives#12]
AS a user
IN ORDER TO view the promoter in the initiative commission 
I NEED the initiative detail page show the promoter committee
CRITERIA OF ACCEPTANCE
- Be able to visualize the components of promoter commitee on the initiative detail page
- Names of the components of the committee will be displayed

**Comment by jsperezg** [comment]
This feature is partially developed. There are several things that should be done before consider it finished:

* The promoter committee should show the controls for accept / reject a member only for the owner and while the initiative is in preparation phase.

* Write tests for the functionality.

**Comment by jsperezg** [comment]
It is not deployed yet. It will be deployed before next thursday.
