### ISSUE TITLE
Detail initiative - Support verified users

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-initiatives#13]
AS a verified user
IN ORDER TO verified users can support an initiative
I NEED the detail page there is a button where verified users can support an initiative
CRITERIA OF ACCEPTANCE
- On the initiative there is a button to support an initiative by verified users
- Supports made by users will increase the number of supports.

**Comment by jsperezg** [comment]
This feature is already developed but it's not finished yet. I still need to write some acceptance tests.

**Comment by jsperezg** [comment]
Needs validation
