### ISSUE TITLE
Detail initiative - Support verified organization

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-initiatives#14]
AS an verified organization
IN ORDED TO verified organizations can support an initiative
I NEED the detail page there is a button where registered organizations can support an initiative
CRITERIA OF ACCEPTANCE
- On the initiative there is a button to support an initiative for verified organizations
- Supports made by organizations will not increase the number of supports.

**Comment by jsperezg** [comment]
This feature has been implemented following the criteria used in Fb. It raises a modal dialog with all verified identities for the user (himself, and each verified organizaion). The user can select wich identity votes/supports the initiative.

**Comment by jsperezg** [comment]
Needs validation
