### ISSUE TITLE
Detail initiative - Share on social networks

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-initiatives#15]
AS a verified user
IN ORDER TO share on social networks
NEED TO be displayed, with the same criteria as in the rest of the portal an option for the user to share it on social networks
CRITERIA OF ACCEPTANCE
It shares the initiative on social networks.

**Comment by jsperezg** [comment]
This feature has been implemented reusing an already existing component in Decidim framework.

**Comment by jsperezg** [comment]
Needs validation
