### ISSUE TITLE
Detail initiative - State initiative

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-initiatives#16]
AS a user
IN ORDER TO show the initiative state
NEED the detail page of the initiative display the current state
      - Insufficient sigantures number
      - Sufficient sigantures number
      - In Process
      - URL related content
CRITERIA OF ACCEPTANCE
- On the initiative detail page show one of the 4 possible Iinitiatives state

**Comment by jsperezg** [comment]
The block showingthe initiative result has been implemented. It needs to be validated.
