### ISSUE TITLE
Detail initiative - minimum number of signatures reached

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-initiatives#17]
AS a user
IN ORDER TO display in the detail initiative page if minimun signature number have been reached
NEED after the signature collection time period has expired show on the detail initiative page the result of the initiative: accepted or rejected

**Comment by jsperezg** [comment]
Already implemented.

**Comment by arnaumonty** [comment]
We Should show the tag Accepted/Rejected using the same use case as proposals:

![captura de pantalla de 2017-11-12 16-22-25](https://user-images.githubusercontent.com/3855859/32700439-b260d1f4-c7c5-11e7-9014-26583db7265c.png)

**Comment by arnaumonty** [comment]
And the same for the initiative page list:
![captura de pantalla de 2017-11-12 16-23-34](https://user-images.githubusercontent.com/3855859/32700445-d9ef5916-c7c5-11e7-8d9d-e4b2234aa288.png)
