### ISSUE TITLE
Admin types initiatives

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-initiatives#19]
AS Admin
IN ORDER TO manage the initiative types
NEED TO have a initiative types list, a button to create a new type and to edit the current
CRITERIA OF ACCEPTANCE
- Have a list of all initiatives types 
- Can access a edition initiative type, edit and save
- Have a button on the list of inicitatives to create a new initiative

**Comment by jsperezg** [comment]
In addition to the previous requirements, the edit form must allow the user to embed videos in the initiative type description.

**Comment by jsperezg** [comment]
Needs validation.
