### ISSUE TITLE
Extend the voting period

### ISSUE THREAD

**Issue by jsperezg** [decidim/decidim-initiatives#22]
Initiative owner should be able to extend the voting period with a justified reason.

**Comment by jsperezg** [comment]
Currently only administrators can change the voting period. I assume that justifying extending this period will happen outside the platform.

**Comment by arnaumonty** [comment]
Would it be possible to give the admins the option to add an extra period of time to collect supports to each initiative?

**Comment by jsperezg** [comment]
Admins already have this privilege. They can change the dates for collecting supports and set them  to any arbitrary  value.
