### ISSUE TITLE
Detail Initiative - Full view

### ISSUE THREAD

**Issue by arnaumonty** [decidim/decidim-initiatives#25]
AS a user
IN ORDER To see full view of each initiative
I NEED to apply the following design
CRITERIA OF ACCEPTANCE

See the following design

![photo5949629169799375323](https://user-images.githubusercontent.com/3855859/31221331-931096f6-a9c3-11e7-93d2-6a3d35765cf3.jpg)

**Comment by jsperezg** [comment]
There are two parts that are missing from the previous mock-up:

* Promoter committee members
* Result of the initiative once it reaches the minimum supports required.

All the other elements are already implemented.

**Comment by arnaumonty** [comment]
- The promoter committee should be the authors of the initiative and it should be located under the Title
- The result should be displayed under the description of the initiative in the same way when we answer a                 proposal ([example](https://decidim-design.herokuapp.com/proposal-view-rejected/)). 
- The size of the title is not correct, should be bigger as a proposal full view.
