### ISSUE TITLE
New Initiative flow

### ISSUE THREAD

**Issue by xabier** [decidim/decidim-initiatives#27]
We have detailed the flow of the initiatives.

Here is an image of how it should look for a user:
![image](https://user-images.githubusercontent.com/537284/31624855-59b63318-b2a4-11e7-8a1d-da5cd2ed2ecf.png)

We propose to add a top guide with the steps shown on the picture throughout the whole process of Initiative Creation. This will help the participants to create an Iniciative, and we can add also some contextual help just bellow. 

Step 4 splits the flow, top: for the individual initiatives that demand the 2 more promoters, and, bottom: for the asociations or collectives. This last one should include the option to upload the document that is required for the Associations to create an Initiative.

Finally step 5 will explain what needs to be done next. This will be special for Barcelona and the abstraction would explain that the user will be prompted to the admin panel.

**Comment by arnaumonty** [comment]
![photo5998856281059863073](https://user-images.githubusercontent.com/3855859/31770725-7f7bcbc6-b4d9-11e7-9a17-10eef25f731f.jpg)
We should create the initiative after 3rd step in order to share the link in 4th step

**Comment by arnaumonty** [comment]
@jsperezg we update all the mockups of the new initiative flow. 
Step1
![new_ic_decidim_paso1](https://user-images.githubusercontent.com/3855859/31820999-ca0a51ce-b5a3-11e7-8c17-46920031070d.png)
Step 2
![new_ic_decidim_paso2](https://user-images.githubusercontent.com/3855859/31821008-d29009d8-b5a3-11e7-9fbd-e740de1824d1.png)
Step 3
![new_ic_decidim_paso3](https://user-images.githubusercontent.com/3855859/31821040-ef3431d6-b5a3-11e7-92a3-5e81b1246029.png)
Step 4
![new_ic_decidim_paso4](https://user-images.githubusercontent.com/3855859/31821047-f84f3748-b5a3-11e7-92c7-e714531069bf.png)
Step 5 - User
![new_ic_decidim_paso5_user](https://user-images.githubusercontent.com/3855859/31821054-044975e0-b5a4-11e7-975f-974bf83fdf5e.png)
Step 5 - Orgs
![new_ic_decidim_paso5_org](https://user-images.githubusercontent.com/3855859/31821068-16653642-b5a4-11e7-831f-86b04ed15e40.png)
Step - 6 Final
![new_ic_decidim_paso6_final](https://user-images.githubusercontent.com/3855859/31821074-1f93e628-b5a4-11e7-873f-d2b4158ffd4f.png)

**Comment by arnaumonty** [comment]
The initial step to choose the type of initiative is missing. We just can keep the present version.

**Comment by jsperezg** [comment]
I've a doubt: In case the initiative is presented by an organization: Should the step 4 and step 5 be filled (one for the user that presents the initiative and another for the organization?)

**Comment by xabier** [comment]
@jsperezg can we make the step 4 "Validation" be configurable on the Initiative configuration panel, for each type of initiative? This step is something we need at Decidim.barcelona but will rarely be required by other organizations. The solution for the generic case is to make it optional. Also there might be cases where Initiative are less demanding in legal-administrative terms, so even for Decidim.barcelona we would like step 4 to be optional for some cases.

**Comment by arnaumonty** [comment]
@jsperezg yes. The official procurement needs someone (a person) who is in charge of the initiative in order to communicate with the organization.

**Comment by xabier** [comment]
Cambiar los títulos de los dos primeros pasos:

Escoge --> Inicia --> Compara ...

![image](https://user-images.githubusercontent.com/537284/31882822-4b8f2058-b7e8-11e7-8385-3ccfbd6dc603.png)
