### ISSUE TITLE
Initiative type detail: we need to improve description of initiative types

### ISSUE THREAD

**Issue by xabier** [decidim/decidim-initiatives#30]
Initiative types have a very short description that is not explanatory. We need to add more explanatory content.

**Comment by arnaumonty** [comment]
For a moment we should redirect to Initiative page list or have something like "read more". Thoughts @jsperezg ??

**Comment by jsperezg** [comment]
This issue is not related to development. The content of the description of each initiative type depends on the administrators of each instance of Decidim.

Since it uses a rich editor you can embed a link to another page or embed a video.
