### ISSUE TITLE
Proceso creación de nueva iniciativa

### ISSUE THREAD

**Issue by BruAguilo** [decidim/decidim-initiatives#33]
Iniciativa > Nueva iniciativa > corrección de texto verde parte superior, que explica la lógica de cada paso.

**Ejemplo**
**PASO**
[link]
_Texto actual_ > Propuesta de texto

**TRIA** **ESCOJE** **CHOOSE**
[https://barcelona-decidim.dev.aspgems.com/create_initiative/select_initiative_type]
_Selecciona el tipus d’iniciativa_ > 
[CAT] Les iniciatives ciutadanes són un mitjà amb el qual la ciutadania intervé a fi que l’Ajuntament dugui a terme una determinada actuació d’interès general i competència municipal. Quina iniciativa vols impulsar?
[ESP] Las iniciativas ciudadanas son un medio con el que la ciudadanía interviene a fin de que el Ayuntamiento lleve a cabo una determinada actuación de interés general y competencia municipal. ¿Qué iniciativa quieres impulsar?
[ENG] Citizen initiatives are a means by which the citizenship can intervene so that the City Council can undertake actions in defence of the general interest that are within fields of municipal jurisdiction. Which initiative do you want to launch? 

**INICIA** **INICIO** **START**
[https://barcelona-decidim.dev.aspgems.com/create_initiative/previous_form?locale=ca]
_Escriu el títol de la teva iniciativa. Et recomanem que el títol siga curt i concis i la descripció centrada en la solució que vols proposar_  > 
[CAT] En què consisteix la iniciativa? Escriu el títol i la descripció. Et recomanem que el títol sigui curt i concís, i la descripció estigui centrada en la solució que es proposa.
[ESP] En qué consiste la iniciativa? Escribe el título y la descripción. Te recomendamos que el título sea corto y conciso, y la descripción esté centrada en la solución que se propone.
[ENG] What does the initiative consist of? Write down the title and description. We recommend a short and concise title and a description focused on the proposed solution. 

(**COMPARA** > salta directamente de INICIA a CREA) 

**CREA** **CREA** **CREATE**
[https://barcelona-decidim.dev.aspgems.com/create_initiative/fill_data?locale=ca]
_- Revisa el contingut de la teva iniciativa_
_- Recorda que la recollida de firmes deu ser digital, presencial o mixta_
_- Tens que sel•leccionar l'àmbit de la teva iniciativa: ciutat, districte, barri, etc..._
_(Mes informació)._
>
[CAT]
-	Revisa el contingut de la teva iniciativa. És entenedor el títol? Queda clar l’objectiu de la iniciativa?
-	Cal seleccionar el tipus de signatura. Presencial, digital o mixta
-	En quin àmbit geogràfic es desenvolupa la iniciativa? Ciutat, districte?
(Mes informació)

[ESP]
- Revisa el contenido de tu iniciativa. ¿Es comprensible el título? ¿Queda claro el objetivo de la iniciativa?
- Hay que seleccionar el tipo de firma. Presencial, digital o mixta
- ¿En qué ámbito geográfico se desarrolla la iniciativa? ¿Ciudad, distrito?
(Más información)

[ENG]
-	Revise the content of your initiative. Is your title easy to understand? Is the objective of your initiative clear?
-	You have to choose the type of signature. In-person, online or a combination of both
-	Which is the geographic scope of the initiative? City, district?
(More information)

**VALIDA** **VALIDA** **VALIDATION**
[https://barcelona-decidim.dev.aspgems.com/create_initiative/validate?locale=ca]
_Ompli els següents camps per validar la iniciativa. Rellena los siguientes campos para validar la iniciativa_
>
[CAT] Omple els següents camps per validar la iniciativa ciutadana
[ESP] Rellena los siguientes campos para validar la iniciativa ciduadana
[ENG] Fill in the following fields in order to validate the citizen initiative

**COMISIÓ > COMISSIÓ PROMOTORA** **COMISIÓN PROMOTORA** **PROMOTING COMMISSION**
[https://barcelona-decidim.dev.aspgems.com/create_initiative/promotal_committee?locale=ca]
_Comparteix el sigüent enllaḉ amb la resta de persones que van a promoure aquesta iniciativa. Quan els teus contactes reben el enllaç deuràn seguir els passos indicats._
_Enllaç per invitar a les persones que formaran part de la comisió promotora_
>
[CAT]
Les iniciatives ciutadanes requereixen una Comissió promotora formada per, com a mínim, tres persones (fedatàries). Cal que comparteixis el següent enllaç amb la resta de persones que promoguin aquesta iniciativa. Quan els teus contactes rebin l’enllaç, hauran de seguir els passos indicats.
Enllaç per convidar a les persones que formaran part de la Comissió promotora 
[ESP]
Las iniciativas ciudadanas requieren una Comisión promotora formada por, al menos, tres personas (fedatarias). Es necesario que compartas el siguiente enlace con el resto de personas que promuevan esta iniciativa. Cuando tus contactos reciban el enlace, deberán seguir los pasos indicados.
Enlace para invitar a las personas que formarán parte de la Comisión promotora
[ENG]
Citizen initiatives require a Promoting Commission consisting of at least three people (attestors). You must share the following link with the other people that are part of this initiative. When your contacts receive this link they will have to follow the indicated steps.

**FINALITZA** **FINALIZA** **FINISH**
[https://barcelona-decidim.dev.aspgems.com/create_initiative/finish?locale=ca]
_Enhorabona! La teua iniciativa s'ha creat amb èxit._ 
_Recorda que per a tramitar correctament la iniciativa tens que accedir al panel d'administració de la teua iniciativa, pujar la informació requerida i enviar-la a tràmit._ 
_- Si eres una associació deuràs pujar l'acta signada dels òrgans de direcció de les organitzacions membres de la Comisió promotora._
_- Si has triat l'opció de recollida de firmes presencial o mixta deuras pujar l'informació requerida._ 
_Pots consultar tota aquesta informació en la pàgina de informació d'iniciatives._ 
_Recorda que sempre podràs accedir a les teues iniciatives des d'el teu menu d'usuari_
>
[CAT]
Enhorabona! La teva iniciativa ciutadana s’ha creat amb èxit.
Recorda que per tramitar correctament la iniciativa cal que accedeixis al panell d’administració que trobaràs al menú d’usuari, pujar la informació requerida i enviar-la a tràmit.
- Si ets una associació, hauràs de pujar l’acta signada dels òrgans de direcció de les organitzacions membres de la Comissió Promotora
- Si has seleccionat l’opció de recollida de firmes presencial o mixta, hauràs de pujar la informació requerida
Pots consultar tota aquesta informació a la pàgina d’informació d’iniciatives
Recorda que sempre podràs accedir a les teves iniciatives des del menú d’usuari

[ESP]
¡Enhorabuena! Tu iniciativa ciudadana se ha creado con éxito.
Recuerda que para tramitar correctamente la iniciativa tienes que acceder al panel de administración que en el menú de usuario, subir la información requerida y enviarla a trámite.
- Si eres una asociación, deberás subir el acta firmada de los órganos de dirección de las organizaciones miembros de la Comisión Promotora
- Si has seleccionado la opción de recogida de firmas presencial o mixta, deberás subir la información requerida
Puedes consultar toda esta información en la página de información de iniciativas
Recuerda que siempre podrás acceder a tus iniciativas desde el menú de usuario

[ENG]
Congratulations! Your citizen initiative has been created successfully.
Remember that in order to properly process the initiative you must access the administration panel where you will find the user menu, upload the information required and send it to procedure. 
-	If you are an association you will have to upload the minutes of the management board of all the organisations that conform the Promoting Commission
-	If you have chosen to collect the signatures in-person or combined with online, you will have to upload the required information.
You can look up all this information on the page dedicated to inform about initiatives
Remember that you will always be able to access your initiatives through the user menu.

**Comment by xabier** [comment]
@BruAguilo muchas gracias por tu contribución

Creo que vamos a necesitar los textos en inglés (que es el idioma principal en el que se desarrollan las funcionalidades de Decidim), espero a que @jsperezg lo certifique. 

en todo caso lo que propones está súper bien, a ver si lo podemos implementar para el testeo masivo del módulo de iniciativas que vamos a hacer la semana que viene

**Comment by jsperezg** [comment]
En efecto, necesitamos los textos en inglés

**Comment by BruAguilo** [comment]
ok, miro de pasároslo en inglés. Entiendo que en ESP también es necesario, ¿no?

**Comment by BruAguilo** [comment]
Cuelgo traducciones que hemos hecho con Lucas Vidal

**Comment by jsperezg** [comment]
I have pushed changes in the repo that fix  this issue. Next  monday I will deploy them  in the staging environment so  you can validate that everything is alright.

**Comment by xabier** [comment]
Los textos son muy buenos. Enhorabuena. Hay un tema pendiente pero voy a abrir otro issue para ello y así no bloqueo esto que está fantástico.

@BruAguilo congratulations, @jsperezg waiting forward to see it in the staging environment soon

**Comment by jsperezg** [comment]
I've just deployed it on staging environment right now. You can proceed with validation whenever you want.
