### ISSUE TITLE
We should have permissions on the type initative list

### ISSUE THREAD

**Issue by arnaumonty** [decidim/decidim-initiatives#38]
In order to control the permissions of the user in different types of initiatives we should  have configurable verification options in each initiative type, as the components have in participatory processes:
![captura de pantalla de 2017-11-12 16-16-08](https://user-images.githubusercontent.com/3855859/32700396-d6675bc8-c7c4-11e7-8c88-350d98818d99.png)

**Comment by jsperezg** [comment]
I don't understand the intent of this issue.

An initiative type is just a value that a user can select from a list. I don't see the needing of managing permissions for initiative types.

**Comment by arnaumonty** [comment]
This is not abou admin permissions, is about who can sign an initiative. We have the use case that maybe in a type of initiatives you have to be verified as a user, but with other type of initiative you need another step validation (sms for example). To do this abstraction this setting should be configurable as proposals or other components.
