### ISSUE TITLE
New initiative - Selection type

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-initiatives#4]
AS a verified user/organization
IN ORDER TO  In the creation of a new initiative, can select the right type of initiative
NEED TO have a page where be all initiative types, a brief explanation and a create initiative button

**Comment by jsperezg** [comment]
Tests pending.

**Comment by jsperezg** [comment]
Needs validation

**Comment by arnaumonty** [comment]
Tha page with all the initiatives types should have:
- Text with the explanation about what is an initiative using highlighted message (like[ this for exampe](https://decidim-design.herokuapp.com/info/)) in the top of the page.
- The ability to decide the order of initiatives in the initiative types page list.
- Adjust the size of embedded video with the panoramic view.
