### ISSUE TITLE
Move PartialTranslationsHelper logic into the main repo and drop it from here

### ISSUE THREAD

**Issue by mrcasals** [decidim/decidim-initiatives#48]
Recently ([\#2204](https://github.com/decidim/decidim/pull/2204)) we changed the logic of translated attributes, and now only the default locale translation is required:

https://github.com/decidim/decidim/blob/b22958710e24aa68a0b976195943b67d7436206d/decidim-core/app/helpers/decidim/translations_helper.rb#L13

We can't have different logic to render these fields in official components, but the logic seems fine (while missing the part of the default locale).

Please send a PR to merge both logics and drop the use of this file in this component.

**Comment by jsperezg** [comment]
This issue is aduplacted of #65
