### ISSUE TITLE
New initiative - Basic fields

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-initiatives#5]
AS a verified user/organization
IN ORDER TO fill in the basic initiative fields 
NEED TO a form where you can fill in the initiative title and description. The type of initiative is selected from the list of similiar initiatives
CRITERIA OF ACCEPTANCE
- The type of initiative comes selected
- Have a form where you enter the title and description of the initiative

**Comment by jsperezg** [comment]
Tests pending.

**Comment by jsperezg** [comment]
Needs validation.

**Comment by arnaumonty** [comment]
- We need contextual help in order to explain each field.
- We need an explanation text before the fields in order to give some tips on creating the initiative.
