### ISSUE TITLE
Move services to `app/services/`

### ISSUE THREAD

**Issue by mrcasals** [decidim/decidim-initiatives#50]
Some classes found in `app/models/` do not act as models but as services, so they should be moved to `app/services/`. Also, they should be scoped under the `Decidim::Initiatives` module:

- `Decidim::InitiativeProgressNotifier` => `Decidim::Initiatives::ProgressNotifier`
- `Decidim::InitiativeStatusChangeNotifier` => `Decidim::Initiatives::StatusChangeNotifier`

**Comment by jsperezg** [comment]
My mistake. I was working on #50, While tests where running I fixed the extra colon in this issue and added the comment.

You have a PR that fixes it.

**Comment by mrcasals** [comment]
There's two commits saying they fix this issue, but one of those doesn't. 

Commit names should explain what they do, not what issue they fix. The best approach is creating a new branch *per issue*, add commits there and create a PR from that branch saying what issue it fixes.

Otherwise tracking the changes is really difficult!
