### ISSUE TITLE
Why not merge `InitiativesExtraData` to `Initiatives`?

### ISSUE THREAD

**Issue by mrcasals** [decidim/decidim-initiatives#51]
Can you explain why you need this data structure and why not join it with the `Initiatives` model? Looks like you wanted to have multiple authors, but why not use a `has_and_belongs_to_many` polymorphic relation?

**Comment by mrcasals** [comment]
Add documentation to the `InitiativesExtraData` to explain why we need it.

**Comment by jsperezg** [comment]
This table will be removed in #52
