### ISSUE TITLE
Views: use I18n module

### ISSUE THREAD

**Issue by mrcasals** [decidim/decidim-initiatives#53]
Under `app/views/decidim/initiatives/create_initiative/` there are a lot of file with a locale extension, only appearing Catalan, Spanish and English, and some of these files have typos.

Please, use the Rails I18n module so that these views can be extended into other locales and fix those typos. If we need to overwrite some of these values for a specific installation we'll do it per installation, but always modifying the locale files, not hardcoding the texts to the views.

**Comment by jsperezg** [comment]
This should be fixed after #52 PR is merged.
