### ISSUE TITLE
Show Initiatives in the homepage

### ISSUE THREAD

**Issue by mrcasals** [decidim/decidim-initiatives#54]
As per https://github.com/decidim/decidim/issues/2062, initiatives should be shown in the homepage. Please check the changes added in https://github.com/decidim/decidim/pull/2114 to see how to achieve it. 

There's an implementation in https://github.com/decidim/decidim/pull/2162

**Comment by jsperezg** [comment]
This feature is outside the initial roadmap of Initiatives and thus out of the mvp as well. We should leave the issue open to take it in consideration for future enhancements of it but IMHO it is something that we don't need right now.

**Comment by mrcasals** [comment]
Issue #86 has a small mockup for how to display them. /cc @xabier
