### ISSUE TITLE
Unify i18n to "sign" an initiative

### ISSUE THREAD

**Issue by mrcasals** [decidim/decidim-initiatives#55]
Catalan translation shows "Signar" and "adhesions":

![](https://i.imgur.com/9agjC6T.png)

English shows "Vote" and "adhesions":

![](https://i.imgur.com/gcXQhKP.png)

Spanish shows "Firmar" annd "adhesiones":

![](https://i.imgur.com/HloOW3U.png)

I think the English word show be changed to "sign", as voting is private but adhering to an initiative will be public.

Pinging @decidim/product for their input.

**Comment by carolromero** [comment]
Agreed @mrcasals, we should use "Sign" and "Signatures" for that matter.
