### ISSUE TITLE
New initiative - Similar initiative

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-initiatives#6]
AS a verified user/organization
IN ORDER TO prevent user from creating duplicate initiatives
NEED TO after filling the title and description fields when creating an initiative, will show whether there are similar initiatives
CRITERIA OF ACCEPTANCE
- If similar initiatives found thet must be presented to the user
- If there are no similar initiatives, the user will be forwarded to continue filling the rest of the required fields

**Comment by jsperezg** [comment]
Tests pending.

**Comment by jsperezg** [comment]
Needs validation.

**Comment by arnaumonty** [comment]
- We need more information in order to understand the action. We should display something like:
"Se han econtrado las siguientes iniciativas similares".

- In the left of button to continue, we should show the following message
"Ninguna de las anteriores iniciativas se ajusta a mi propuesta"
