### ISSUE TITLE
Port `PartialTranslatedAttribute` to main repo

### ISSUE THREAD

**Issue by mrcasals** [decidim/decidim-initiatives#65]
The logic form the `PartialTranslatedAttribute` does not match the current logic in the main repo, and it might cause inconsistent results.

We recently changed the logic for translated attributes (https://github.com/decidim/decidim/pull/2204), and now we're only requiring the default locale. If a user visits the website in another locale which has no translation, we show the default one. If the default one does not have any context, we show nothing.

We could merge the logic from the main repo with this:

https://github.com/decidim/decidim-initiatives/blob/3e0a056d726b0cf2fcf6ae4841a31da8256aa80f/lib/decidim/partial_translations_helper.rb#L19-L21

This way, we would show this to the user:

1. The current locale trannslation
1. The default locale translation
1. The first locale we find with a translation.
1. An empty string

Changes should be made here:

https://github.com/decidim/decidim/blob/95a4a0356221a1a6920f211ba5969b7b95d58733/decidim-core/app/helpers/decidim/translations_helper.rb#L13-L17

**Comment by jsperezg** [comment]
If this feature is in a stable release we can consider doing it. Otherwise this is something that we should done after 0.8.0 becomes stable and we bump to this version.

**Comment by mrcasals** [comment]
https://github.com/decidim/decidim/pull/2204 has been published at decidim 0.8.0 version 😄

**Comment by jsperezg** [comment]
partially translated attribute can be safely replaced by the standard translated_attribute provided in Decidim 0.9 and higher versions. IMHO we should close this issue

**Comment by oriolgual** [comment]
Closed by #118
