### ISSUE TITLE
New initiative - Review similar initiatives

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-initiatives#7]
AS a verified user/organization
IN ORDER TO complete the scope  of the initiative
NEED TO If  no similar initiatives found, The user can review/correct the title and description filled previously. Additionally the user must fill the following fields: Scope of the initiative. Signature/support type (online, face-to-face, mixed). In case the user represents a verified organization he/she must select who will be the author of the initiative (the user or the organization).

**Comment by jsperezg** [comment]
Tests pending.

**Comment by jsperezg** [comment]
Needs validation.
