### ISSUE TITLE
Missing host in mailer

### ISSUE THREAD

**Issue by josepjaume** [decidim/decidim-initiatives#79]
# This is a Bug Report

#### :tophat: Description
The host is missing when building URLs on the initiatives mailer. Check out this exception we received in `metadecidim`: https://sentry.io/share/issue/e271fa59939c42a8a25cc356e144ded5/

#### :pushpin: Related issues
*None*

#### :clipboard: Additional Data

* ***Decidim deployment where you found the issue***: Metadecidim
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:

**Comment by josepjaume** [comment]
@jsperezg, @arnaumonty check this out.

**Comment by jsperezg** [comment]
This is a Metadecidim's configuration issue. Check the action mailer manual, section 2.7:

2.7 Generating URLs in Action Mailer Views
Unlike controllers, the mailer instance doesn't have any context about the incoming request so you'll need to provide the :host parameter yourself.

As the :host usually is consistent across the application you can configure it globally in config/application.rb:

```ruby
config.action_mailer.default_url_options = { host: 'example.com' }
```

**Comment by mrcasals** [comment]
@jsperezg Decidim is multi-tenant, and each organization can have a different host. If we set this up in an initializer, then we cannot change it per organization, so it needs to be set at the view level, using the organization.

For example, see this view:

https://github.com/decidim/decidim/blob/master/decidim-core/app/views/devise/mailer/confirmation_instructions.html.erb

**Comment by jsperezg** [comment]
Understood! I will prepare a patch for this issue
