### ISSUE TITLE
New initiative - Initiative Preview

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-initiatives#8]
AS a verified user
IN ORDER TO Review a initiative before publishing it
NEED TO You can view the page with the details entered for an initiative.
CRITERIA OF ACCEPTANCE
- The user who created the initiative has the option to preview the initiative.
- Preview the initiative with all fields filled

**Comment by jsperezg** [comment]
Preview is available at the administration area.

Needs validation.
