### ISSUE TITLE
Undefined method `partially_translated_attribute`

### ISSUE THREAD

**Issue by mrcasals** [decidim/decidim-initiatives#80]
# This is a Bug Report

#### :tophat: Description
We're getting reports of a missing `partially_translated_attribute` method:

https://sentry.io/share/issue/47626b2e43ef4d3a90721ca8e5bd7d96/

#### :pushpin: Related issues
* #65

**Comment by jsperezg** [comment]
I'm gonna close this issue since the referred method has been removed from the sources.
