### ISSUE TITLE
Random sample of iniciatives at home page

### ISSUE THREAD

**Issue by xabier** [decidim/decidim-initiatives#86]
# This is a Feature proposal

We need to display a random set of 4-8 iniciatives at the home page of the platform, in random order as well (to provide all iniciatives with the same oportunities to be seen). 

This needs to be displayed like Processes or Assemblies

![image](https://user-images.githubusercontent.com/537284/34099575-28fdebb8-e3e0-11e7-9f22-0d9c173cc336.png)

**Comment by mrcasals** [comment]
@xabier see #54, which has a reply from @jsperezg
