### ISSUE TITLE
Fix model name

### ISSUE THREAD

**Issue by oriolgual** [decidim/decidim-initiatives#89]
# This is a Bug Report

#### :tophat: Description

In order to follow the naming convention at Decidim the `Initiative` model should be re-scoped to `Decidim::Initiatives::Initiative` instead of `Decidim::Initiative`.

We should also add a migration to rename the database table.

**Comment by jsperezg** [comment]
IMHO this  is not an issue. Check the convention for first level engines: assemblies and participatory  processes. All  of them  live inside Decidim namespace.

**Comment by josepjaume** [comment]
Hmmm, well this definitely sits on middle ground. While all the plain models from other modules are scoped, it's true that participatory spaces are top-level. And an `Initiative` is both things at the same time.

Is this blocking you for some reason, @oriolgual ?

**Comment by oriolgual** [comment]
Not at all, I guess I didn't thought an initiative could be both things. Let's keep it like this then.
