### ISSUE TITLE
Details initiative - Basic information

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-initiatives#9]
AS a user
IN ORDER TO see basic information ( initiative title, type and description ) and the range of validity (date, deadline collect signatures)
NEED  the detail page of the initiative is shown the initiative type, title, description and signature collection time interval
CRITERIA OF ACCEPTANCE
- Can view the type of initiative, title, description, signature collection time interval

**Comment by jsperezg** [comment]
Almost finished. Pending tasks:

* Check that UI fits on requirements.
* Write tests.

**Comment by jsperezg** [comment]
Needs validation
