### ISSUE TITLE
[BUG] Multiple initiatives with the same title has been created 

### ISSUE THREAD

**Issue by arnaumonty** [decidim/decidim-initiatives#97]
# This is a Bug Report 

Multiple initiatives with the same title has been created and it looks like an error.

#### :tophat: Description

For bug reports:
* What went wrong? Several initatives has been created at the same time.
* What did you expect should have happened? Just to have one
* What was the config you used? From Admin
* What stacktrace or error message from your provider did you see? 

#### :clipboard: Additional Data

* ***Decidim deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:
![image](https://user-images.githubusercontent.com/3855859/34827027-17d191bc-f6d9-11e7-9f0a-2db0a393fffe.png)

* ***Error messages***:
* ***URL to reproduce the error***:
/admin/initiatives

**Comment by jsperezg** [comment]
Add data-disable-with to the submit button that creates the initiative

**Comment by mrcasals** [comment]
I did something similar a while ago at `decidim`: https://github.com/decidim/decidim/pull/2379 You can copy the code from there
