### ISSUE TITLE
decidim-initatives US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by bishalkc** [decidim/decidim-initiatives#99]
with gem "decidim-initiatives", git: "https://github.com/decidim/decidim-initiatives" in Gemfile

I am getting following error: 

/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/dsl.rb:551:in `parse_line_number_from_description': invalid byte sequence in US-ASCII (ArgumentError)

Work around is 
export LC_ALL=C.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

and run bundle

**Comment by jsperezg** [comment]
Thanks for your report @bishalkc 

We've removed all accents in the gemspec file. This will be fixed soon.
